# Generated by Django 5.2.1 on 2025-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_device_remove_task_projects_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='Dirección MAC')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
            ],
        ),
    ]
