# Generated by Django 5.2.1 on 2025-05-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alloweddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
            ],
        ),
    ]
