# Generated by Django 5.2.1 on 2025-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_whitelistdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
