# Generated by Django 5.2.1 on 2025-06-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_device_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
