# Generated by Django 5.2.1 on 2025-06-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraficoPorMinuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('minuto', models.CharField(max_length=16)),
                ('bytes', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
