# Generated by Django 5.2.1 on 2025-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_traficoporminuto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traficoporminuto',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='traficoporminuto',
            name='bytes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='traficoporminuto',
            name='mac',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traficoporminuto',
            name='minuto',
            field=models.DateTimeField(),
        ),
    ]
