# Generated by Django 5.2.1 on 2025-06-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_traficoporminuto_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhitelistDevice',
        ),
        migrations.AlterModelOptions(
            name='traficoporminuto',
            options={'verbose_name': 'Tráfico por minuto', 'verbose_name_plural': 'Tráfico por minuto'},
        ),
        migrations.AlterField(
            model_name='traficoporminuto',
            name='mac',
            field=models.CharField(max_length=17),
        ),
        migrations.AddIndex(
            model_name='traficoporminuto',
            index=models.Index(fields=['mac', 'minuto'], name='board_trafi_mac_6de97e_idx'),
        ),
    ]
