# Generated by Django 5.2.1 on 2025-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFalso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('host', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
