# Generated by Django 5.2.1 on 2025-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_loginfalso'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfalso',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
