# Generated by Django 5.2.1 on 2025-06-20 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_loginfalso_user_agent_alter_loginfalso_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfalso',
            name='clave',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='path',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='user_agent',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='loginfalso',
            name='usuario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
