# Generated by Django 5.2.1 on 2025-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_loginfalso_clave_alter_loginfalso_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfalso',
            name='mac',
            field=models.CharField(default='', max_length=100),
        ),
    ]
