# Generated by Django 5.2.1 on 2025-06-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_loginfalso_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfalso',
            name='mac',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17),
        ),
    ]
