# Generated by Django 5.2.1 on 2025-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_loginfalso_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfalso',
            name='mac',
            field=models.CharField(default='', max_length=100),
        ),
    ]
