# Generated by Django 5.2.1 on 2025-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_macipcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ap_conectado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macipcache',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='macipcache',
            name='mac',
            field=models.CharField(max_length=17),
        ),
    ]
