# Generated by Django 5.2.1 on 2025-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_device_ap_conectado_alter_macipcache_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ap_conectado',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
