# Generated by Django 5.2.1 on 2025-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_alter_device_ap_conectado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ap_conectado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
