# Generated by Django 5.2.1 on 2025-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_alter_device_ap_conectado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.GenericIPAddressField(),
        ),
    ]
