# Generated by Django 5.2.1 on 2025-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_device_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ap_conectado',
        ),
        migrations.AddField(
            model_name='device',
            name='access_point_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
