# Generated by Django 5.2.1 on 2025-06-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_remove_device_ap_conectado_device_access_point_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='access_point_ip',
            new_name='ap_conectado',
        ),
    ]
